### ISSUE TITLE
Saving the state of the water

### ISSUE THREAD

**Issue by RaptorRaptures** [bshishov/UnityTerrainErosionGPU#6]
Hi bshishov,

Again thanks for this project. 

Can you please advise on how one can go about saving the state of the water? My main goal is serialize this and add it to a file in order to recall it at a later point.

**Comment by bshishov** [comment]
Hello, 

to save the state - simply save the _stateTexture (which is a rendertexture):

Save:
- Blit state texture to texture2D
- save texture to disk (png or smth)

Load:
- load texture2d from disk
- blit texture2d to state texture

however note texture format (ARGB float)
so probably just a plain binary format might be better because texture values could exceed 0-255
